package Common;

public enum TipoMensaje {
    ASIGNAR_NUEVO_PUERTO,
    CERRAR_SESION,
    CONEXION,
    CONFIRMACION_CIERRE,
    CONFIRMACION_CONEXION,
    LISTA_USUARIOS,
    PREPARADOR_SERVIDOR_CLIENTE_RECEPTOR,
    PUERTO_P2P_NO_DISPONIBLE,
    SOLICITUD_DESCARGA,
    PREPARADO,
    SOLICITUD_LISTA

}
